### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

###

GET http://localhost:3000/v1/videos/este-es-un-parametro
Accept: application/json
User-Agent: IntelliJ HTTP Client/WebStorm 2024.3.2.1
Accept-Encoding: br, deflate, gzip, x-gzip

###

POST localhost:3000/v1/videos
Content-Type: application/json

{
  "title": "Holasdsdf",
  "description": "mundo",
  "src": "content"
}

###
# curl --location 'localhost:3000/v1/courses'
#--header 'Content-Type: application/json'
#--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjI5YzMyYjNmN2U3YzRmMDljN2Q5OSIsImlhdCI6MTczOTgyODQyMSwiZXhwIjoxNzM5OTE0ODIxfQ.614MDRaWsD1O1-e5WbKOdMztaWsxvvHc0hg-I5I35LY'
#--data '{
#  "title": "Holasdsdf sfsd fsd fsdfs dfsdfsdf",
#  "price": 300,
#  "description": "mundo",
#  "coverImage": "http://ww.image.com/index.png"
#}'
POST localhost:3000/v1/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjI5YzMyYjNmN2U3YzRmMDljN2Q5OSIsImlhdCI6MTczOTkxODY3MSwiZXhwIjoxNzQwMDA1MDcxfQ.22cAzzm66F_X2K0Kuh-0bCSWfalhwShdNnabPPU_b94
Content-Type: application/json

{
  "title": "Curso Udemy",
  "price": 300,
  "description": "Buen tutorial",
  "coverImage": "http://ww.image.com/index.png"
}

###
GET localhost:3000/v1/courses/67b41b9dbfa5b599c0cbdbb0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjYzYTY4ZDA5MzIzOTEzNjQ1YmE2MiIsImlhdCI6MTczOTk5NTg1MSwiZXhwIjoxNzQwMDgyMjUxfQ.T5I8IUl-7tUqN5szRFDEm4C4Qym8QbLO2y2ray_RD7w
Content-Type: application/json

###

###
GET localhost:3000/v1/courses/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjYzYTY4ZDA5MzIzOTEzNjQ1YmE2MiIsImlhdCI6MTczOTk5NTg1MSwiZXhwIjoxNzQwMDgyMjUxfQ.T5I8IUl-7tUqN5szRFDEm4C4Qym8QbLO2y2ray_RD7w
Content-Type: application/json

###
# curl --location 'http://localhost:3000/v1/videos/upload'
#--header 'accept: */*'
#--form 'image=@"/home/roberto/Pictures/Screenshots/Screenshot from 2025-02-05 16-57-22.png"'
POST http://localhost:3000/v1/videos/upload
accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="Screenshot from 2025-02-05 16-57-22.png""

< /home/roberto/Pictures/Screenshots/Screenshot from 2025-02-05 16-57-22.png
--WebAppBoundary--

###

###
POST localhost:3000/v1/auth/register
Content-Type: application/json

{
  "email": "maniac787@gmail.com",
  "name": "Roberto Chasipanta",
  "password": "MiCLave123",
  "roles": ["user"]
}

###
POST localhost:3000/v1/auth/login
Content-Type: application/json

{
  "email": "maniac787@gmail.com",
  "password": "MiCLave123"
}