### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

###

GET http://localhost:3000/v1/videos/este-es-un-parametro
Accept: application/json
User-Agent: IntelliJ HTTP Client/WebStorm 2024.3.2.1
Accept-Encoding: br, deflate, gzip, x-gzip

###

POST localhost:3000/v1/videos
Content-Type: application/json

{
  "title": "Holasdsdf sfsd fsd fsdfs dfsdfsdf",
  "description": "mundo",
  "src": "content"
}

###
POST localhost:3000/v1/courses
Content-Type: application/json

{
  "title": "Holasdsdf sfsd fsd fsdfs dfsdfsdf",
  "price": 300,
  "description": "mundo",
  "coverImage": "http://ww.image.com/index.png"
}

###
GET localhost:3000/v1/courses/El mejor libro del mundo
Content-Type: application/json

###
# curl --location 'http://localhost:3000/v1/videos/upload'
#--header 'accept: */*'
#--form 'image=@"/home/roberto/Pictures/Screenshots/Screenshot from 2025-02-05 16-57-22.png"'
POST http://localhost:3000/v1/videos/upload
accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="Screenshot from 2025-02-05 16-57-22.png""

< /home/roberto/Pictures/Screenshots/Screenshot from 2025-02-05 16-57-22.png
--WebAppBoundary--

###

