### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

###

GET http://localhost:3000/videos?id=1
Accept: application/json
User-Agent: IntelliJ HTTP Client/WebStorm 2024.3.2.1
Accept-Encoding: br, deflate, gzip, x-gzip

###

POST localhost:3000/videos
Content-Type: application/json

{
  "title": "Holasdsdf sfsd fsd fsdfs dfsdfsdf",
  "description": "mundo",
  "src": "content"
}

###
POST localhost:3000/v1/courses
Content-Type: application/json

{
  "title": "Holasdsdf sfsd fsd fsdfs dfsdfsdf",
  "price": 300,
  "description": "mundo",
  "coverImage": "http://ww.image.com/index.png"
}
